Feat/cqrs pattern
restmark/goauth pull request #1
Opened 2018-05-01 20:09 UTC by maxencehenneron

2018-05-01 20:10 UTC, maxencehenneron commented
wip, do not merge

2018-05-03 10:12 UTC, adrien3d requested changes

2018-05-03 10:12 UTC, adrien3d commented on controllers/user_test.go
> +	"github.com/spf13/viper"
Un `go fmt`?

2018-05-03 10:12 UTC, adrien3d commented on helpers/params/params.go
> +type M map[string]interface{}
Sert à quoi?

2018-05-03 10:12 UTC, adrien3d commented on models/user.go
> +	Firstname string `json:"first_name" bson:"first_name" valid:"required"`
Je préfèrerais firstname, par consistance avec le SanitizedUser.

2018-05-03 10:12 UTC, adrien3d commented on models/user.go
> +	Lastname  string `json:"last_name" bson:"last_name" valid:"required"`
Je préfèrerais lastname, par consistance avec le SanitizedUser.

2018-05-03 10:12 UTC, adrien3d commented on server/consumer.go
> +
Le customer sert à quoi?

2018-05-03 10:12 UTC, adrien3d commented on server/topicrouter.go
> +		mongodb.New(api.Database), //TODO: Remove mongodb dependency and create store from configuration
Faire un layer d'abstaction pour la TODO?

2018-05-03 10:12 UTC, adrien3d commented on server/router.go
>  	router.Use(middlewares.KafkaMiddleware(a.Kafka))
Rajouter les routes FindUser, FindUserById et UpdateUser?

2018-05-03 10:12 UTC, adrien3d commented on server/consumer.go
> +	topics := []string{a.Config.GetString("kafka_topic")}
Du coup on ne subscribe qu'au topic auth ?

2018-05-03 10:56 UTC, maxencehenneron commented on controllers/user_test.go
> +	"github.com/spf13/viper"
? "s" est après "r" dans l'alphabet

2018-05-03 10:59 UTC, maxencehenneron commented on server/topicrouter.go
> +		mongodb.New(api.Database), //TODO: Remove mongodb dependency and create store from configuration
Il existe déjà, faudrait juste choisir le bon store en fonction d'un fichier de config par exemple

2018-05-03 11:09 UTC, maxencehenneron commented on server/router.go
>  	router.Use(middlewares.KafkaMiddleware(a.Kafka))
sujet d'une autre PR

2018-05-03 11:09 UTC, maxencehenneron commented on server/consumer.go
> +	topics := []string{a.Config.GetString("kafka_topic")}
actuellement oui, mais dans la PR où j'implémenterai la modification d'un user ou sa suppression j'ajouterai d'autre topics

2018-05-03 11:12 UTC, maxencehenneron commented on models/user.go
> +	Lastname  string `json:"last_name" bson:"last_name" valid:"required"`
bien vu pour la consistance, modifié. Par contre j'ai gardé la séparation avec "_" car c'est la convention JSON.

2018-05-03 11:13 UTC, maxencehenneron commented on models/user.go
> +	Firstname string `json:"first_name" bson:"first_name" valid:"required"`
voir comment en dessous

2018-05-03 11:14 UTC, maxencehenneron commented on helpers/params/params.go
> +type M map[string]interface{}
Abstraction des paramètres, utilisé notamment pour faire abstraction des critères dans une query de bdd.

2018-05-03 11:15 UTC, maxencehenneron commented on server/consumer.go
> +
C'est "consumer", c'est ce qui traite les messages venant de kafka

2018-05-03 14:08 UTC, adrien3d commented on controllers/user_test.go
> +	"github.com/spf13/viper"
Oui, je demandais juste si c'était généré par `go fmt`

2018-05-03 14:16 UTC, adrien3d approved these changes

2018-05-03 14:16 UTC, adrien3d commented on helpers/params/params.go
> +type M map[string]interface{}
Okay.

2018-05-03 14:16 UTC, adrien3d commented on models/user.go
> +	Lastname  string `json:"last_name" bson:"last_name" valid:"required"`
ah d'accord.

2018-05-03 15:37 UTC, merged